name: Verify CI
run-name: "Verify ${{ github.event.pull_request && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || format('{1}: {0}', github.event.head_commit.message, github.ref) }}"

on:
  pull_request:
    branches: [main]
  push:
  workflow_call:

env:
  RUNTIME: node@26

jobs:
  verify:
    needs:
      - fmtcheck
      - typecheck
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Do you like gradients?'

  fmtcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: ${{ env.RUNTIME }}
      - run: pnpm fmtcheck

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: ${{ env.RUNTIME }}
      - run: pnpm build
      - run: node scripts/copy_sources.ts
      - run: pnpm exec playwright install --with-deps
      - run: pnpm exec playwright test
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: ${{ env.RUNTIME }}
      - run: pnpm typecheck
